### PR TITLE
added homepage, login and signup

### PR DESCRIPTION
**Pull request by nisargpawade**
- added homepage
- added login page
- added signup page

image
image
image

### CODE REVIEW

**Comment by apoorvshrimali** [comment]
amazing ui 
just one suggestion try adding shadow to boxes it will look much cooler.

**Review by anshulraheja — APPROVED** [review]
Everything looks great. You can merge the code

**Review by abhijeetekad — APPROVED** [review]
The code looks fine but the general suggestion try to make the page responsive.

**Comment by nisargpawade** [comment]
> The code looks fine but the general suggestion try to make the page responsive.

will do so after completing everything else

**Comment by nisargpawade** [comment]
> amazing ui just one suggestion try adding shadow to boxes it will look much cooler.

I did add box shadows

**Pull request merged**
